CREATE TABLE MEMO (
  ID NUMBER PRIMARY KEY,
  PROJECT_ID NUMBER NOT NULL,
  TITLE VARCHAR2(255),
  CONTENT CLOB,
  MODIFYTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  WRITTER VARCHAR2(100)
);
select * from memo;

CREATE SEQUENCE memo_seq START WITH 1 INCREMENT BY 1 NOCACHE;