-- 프로젝트 멤버(소프트 삭제 방식)
CREATE TABLE PROJECT_MEMBER (
  ID          NUMBER PRIMARY KEY,
  PROJECT_ID  NUMBER NOT NULL,
  USER_ID     NUMBER NOT NULL,
  ROLE        VARCHAR2(20) NOT NULL,         -- OWNER / ADMIN / MEMBER / VIEWER
  STATUS      VARCHAR2(20) DEFAULT 'ACTIVE', -- ACTIVE / REMOVED
  JOINED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
  LEFT_AT     TIMESTAMP,
  CONSTRAINT UK_PM UNIQUE (PROJECT_ID, USER_ID)
);

select * from project_member;

CREATE SEQUENCE SEQ_PROJECT_MEMBER START WITH 1;

-- 조회 성능 인덱스
--CREATE INDEX IX_PM_PROJ_STATUS ON PROJECT_MEMBER(PROJECT_ID, STATUS);

select * from users;

desc users;

desc users_seq;

-- NUMBER → VARCHAR2 로 변경
ALTER TABLE PROJECT_MEMBER MODIFY USER_ID VARCHAR2(100);