CREATE TABLE TaskMember (
    id NUMBER PRIMARY KEY,
    schedule_Id NUMBER NOT NULL,
    user_Id VARCHAR2(50) NOT NULL,
    name VARCHAR2(50) NOT NULL
);
CREATE SEQUENCE SEQ_TASK_MEMBER START WITH 1;