CREATE TABLE TaskMember (
    id NUMBER PRIMARY KEY,
    schedule_Id NUMBER NOT NULL,
    user_Id VARCHAR2(50) NOT NULL,
    name VARCHAR2(50) NOT NULL
);
CREATE SEQUENCE SEQ_TASK_MEMBER
START WITH 101 -- 최대값 + 1 로 설정
INCREMENT BY 1
NOCACHE
NOCYCLE;